// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 0);
    bufp->chgBit(oldp+0,(vlSelfRef.clk_i));
    bufp->chgBit(oldp+1,(vlSelfRef.rst_i));
    bufp->chgBit(oldp+2,(vlSelfRef.top__DOT__clk_i));
    bufp->chgBit(oldp+3,(vlSelfRef.top__DOT__rst_i));
    bufp->chgWData(oldp+4,(vlSelfRef.top__DOT__imem_req),73);
    bufp->chgQData(oldp+7,(vlSelfRef.top__DOT__imem_rsp),41);
    bufp->chgWData(oldp+9,(vlSelfRef.top__DOT__dmem_req),73);
    bufp->chgQData(oldp+12,(vlSelfRef.top__DOT__dmem_rsp),41);
    bufp->chgBit(oldp+14,(vlSelfRef.top__DOT__imem_req_valid));
    bufp->chgBit(oldp+15,(vlSelfRef.top__DOT__imem_rsp_valid));
    bufp->chgBit(oldp+16,(vlSelfRef.top__DOT__imem_rsp_ready));
    bufp->chgBit(oldp+17,(vlSelfRef.top__DOT__dmem_req_valid));
    bufp->chgBit(oldp+18,(vlSelfRef.top__DOT__dmem_req_ready));
    bufp->chgBit(oldp+19,(vlSelfRef.top__DOT__dmem_rsp_valid));
    bufp->chgBit(oldp+20,(vlSelfRef.top__DOT__dmem_rsp_ready));
    bufp->chgBit(oldp+21,(vlSelfRef.top__DOT__core_inst__DOT__clk_i));
    bufp->chgBit(oldp+22,(vlSelfRef.top__DOT__core_inst__DOT__rst_i));
    bufp->chgBit(oldp+23,(vlSelfRef.top__DOT__core_inst__DOT__imem_rsp_valid_i));
    bufp->chgQData(oldp+24,(vlSelfRef.top__DOT__core_inst__DOT__imem_rsp_i),41);
    bufp->chgQData(oldp+26,(vlSelfRef.top__DOT__core_inst__DOT__dmem_rsp_i),41);
    bufp->chgBit(oldp+28,(vlSelfRef.top__DOT__core_inst__DOT__imem_req_valid_o));
    bufp->chgBit(oldp+29,(vlSelfRef.top__DOT__core_inst__DOT__imem_rsp_ready_o));
    bufp->chgWData(oldp+30,(vlSelfRef.top__DOT__core_inst__DOT__imem_req_o),73);
    bufp->chgWData(oldp+33,(vlSelfRef.top__DOT__core_inst__DOT__dmem_req_o),73);
    bufp->chgCData(oldp+36,(vlSelfRef.top__DOT__core_inst__DOT__rs1_addr),5);
    bufp->chgCData(oldp+37,(vlSelfRef.top__DOT__core_inst__DOT__rs2_addr),5);
    bufp->chgCData(oldp+38,(vlSelfRef.top__DOT__core_inst__DOT__rd_addr),5);
    bufp->chgIData(oldp+39,(vlSelfRef.top__DOT__core_inst__DOT__rd_data),32);
    bufp->chgBit(oldp+40,(vlSelfRef.top__DOT__core_inst__DOT__rd_we));
    bufp->chgIData(oldp+41,(vlSelfRef.top__DOT__core_inst__DOT__rs1_data),32);
    bufp->chgIData(oldp+42,(vlSelfRef.top__DOT__core_inst__DOT__rs2_data),32);
    bufp->chgQData(oldp+43,(vlSelfRef.top__DOT__core_inst__DOT__pc_redirect),33);
    bufp->chgWData(oldp+45,(vlSelfRef.top__DOT__core_inst__DOT__if_id),65);
    bufp->chgCData(oldp+48,(vlSelfRef.top__DOT__core_inst__DOT__ctrl_if),4);
    bufp->chgBit(oldp+49,(vlSelfRef.top__DOT__core_inst__DOT__info_if));
    bufp->chgWData(oldp+50,(vlSelfRef.top__DOT__core_inst__DOT__id_ex),201);
    bufp->chgCData(oldp+57,(vlSelfRef.top__DOT__core_inst__DOT__ctrl_id),3);
    bufp->chgBit(oldp+58,(vlSelfRef.top__DOT__core_inst__DOT__info_id));
    bufp->chgWData(oldp+59,(vlSelfRef.top__DOT__core_inst__DOT__ex_mem),186);
    bufp->chgWData(oldp+65,(vlSelfRef.top__DOT__core_inst__DOT__ctrl_ex),77);
    bufp->chgWData(oldp+68,(vlSelfRef.top__DOT__core_inst__DOT__mem_wb),186);
    bufp->chgBit(oldp+74,(vlSelfRef.top__DOT__core_inst__DOT__ctrl_mem));
    bufp->chgQData(oldp+75,(vlSelfRef.top__DOT__core_inst__DOT__info_mem),38);
    bufp->chgBit(oldp+77,(vlSelfRef.top__DOT__core_inst__DOT__info_wb));
    bufp->chgBit(oldp+78,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__clk_i));
    bufp->chgBit(oldp+79,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__rst_i));
    bufp->chgCData(oldp+80,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__rs1_addr_i),5);
    bufp->chgCData(oldp+81,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__rs2_addr_i),5);
    bufp->chgCData(oldp+82,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__rd_addr_i),5);
    bufp->chgIData(oldp+83,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__rd_data_i),32);
    bufp->chgBit(oldp+84,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__rd_we_i));
    bufp->chgIData(oldp+85,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__rs1_data),32);
    bufp->chgIData(oldp+86,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__rs2_data),32);
    bufp->chgIData(oldp+87,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[0]),32);
    bufp->chgIData(oldp+88,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[1]),32);
    bufp->chgIData(oldp+89,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[2]),32);
    bufp->chgIData(oldp+90,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[3]),32);
    bufp->chgIData(oldp+91,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[4]),32);
    bufp->chgIData(oldp+92,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[5]),32);
    bufp->chgIData(oldp+93,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[6]),32);
    bufp->chgIData(oldp+94,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[7]),32);
    bufp->chgIData(oldp+95,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[8]),32);
    bufp->chgIData(oldp+96,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[9]),32);
    bufp->chgIData(oldp+97,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[10]),32);
    bufp->chgIData(oldp+98,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[11]),32);
    bufp->chgIData(oldp+99,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[12]),32);
    bufp->chgIData(oldp+100,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[13]),32);
    bufp->chgIData(oldp+101,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[14]),32);
    bufp->chgIData(oldp+102,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[15]),32);
    bufp->chgIData(oldp+103,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[16]),32);
    bufp->chgIData(oldp+104,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[17]),32);
    bufp->chgIData(oldp+105,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[18]),32);
    bufp->chgIData(oldp+106,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[19]),32);
    bufp->chgIData(oldp+107,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[20]),32);
    bufp->chgIData(oldp+108,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[21]),32);
    bufp->chgIData(oldp+109,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[22]),32);
    bufp->chgIData(oldp+110,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[23]),32);
    bufp->chgIData(oldp+111,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[24]),32);
    bufp->chgIData(oldp+112,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[25]),32);
    bufp->chgIData(oldp+113,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[26]),32);
    bufp->chgIData(oldp+114,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[27]),32);
    bufp->chgIData(oldp+115,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[28]),32);
    bufp->chgIData(oldp+116,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[29]),32);
    bufp->chgIData(oldp+117,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[30]),32);
    bufp->chgIData(oldp+118,(vlSelfRef.top__DOT__core_inst__DOT__regfile_inst__DOT__regs[31]),32);
    bufp->chgBit(oldp+119,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__clk_i));
    bufp->chgBit(oldp+120,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__rst_i));
    bufp->chgWData(oldp+121,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__ctrl_ex_i),77);
    bufp->chgWData(oldp+124,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__id_ex_i),201);
    bufp->chgQData(oldp+131,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__pc_redirect_o),33);
    bufp->chgWData(oldp+133,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__ex_mem_o),186);
    bufp->chgQData(oldp+139,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__pc_redirect_d),33);
    bufp->chgQData(oldp+141,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__pc_redirect_q),33);
    bufp->chgWData(oldp+143,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__ex_mem_d),186);
    bufp->chgWData(oldp+149,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__ex_mem_q),186);
    bufp->chgIData(oldp+155,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_a),32);
    bufp->chgIData(oldp+156,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_b),32);
    bufp->chgIData(oldp+157,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_q),32);
    bufp->chgBit(oldp+158,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_eq));
    bufp->chgBit(oldp+159,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_lt));
    bufp->chgBit(oldp+160,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_ltu));
    bufp->chgIData(oldp+161,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__rs1_data),32);
    bufp->chgIData(oldp+162,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__rs2_data),32);
    bufp->chgIData(oldp+163,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_inst__DOT__a_i),32);
    bufp->chgIData(oldp+164,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_inst__DOT__b_i),32);
    bufp->chgCData(oldp+165,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_inst__DOT__op_i),4);
    bufp->chgIData(oldp+166,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_inst__DOT__q_o),32);
    bufp->chgBit(oldp+167,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_inst__DOT__eq_o));
    bufp->chgBit(oldp+168,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_inst__DOT__lt_o));
    bufp->chgBit(oldp+169,(vlSelfRef.top__DOT__core_inst__DOT__stage_ex_inst__DOT__alu_inst__DOT__ltu_o));
    bufp->chgBit(oldp+170,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__clk_i));
    bufp->chgBit(oldp+171,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__rst_i));
    bufp->chgCData(oldp+172,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__ctrl_id_i),3);
    bufp->chgWData(oldp+173,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__if_id_i),65);
    bufp->chgIData(oldp+176,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__rs1_data_i),32);
    bufp->chgIData(oldp+177,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__rs2_data_i),32);
    bufp->chgCData(oldp+178,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__rs1_addr_o),5);
    bufp->chgCData(oldp+179,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__rs2_addr_o),5);
    bufp->chgBit(oldp+180,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__info_id_o));
    bufp->chgWData(oldp+181,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__id_ex_o),201);
    bufp->chgWData(oldp+188,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__id_ex_d),201);
    bufp->chgWData(oldp+195,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__id_ex_q),201);
    bufp->chgIData(oldp+202,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__ctrl_signals),20);
    bufp->chgCData(oldp+203,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__instr_type),3);
    bufp->chgBit(oldp+204,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__eraise));
    bufp->chgBit(oldp+205,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__illegal));
    bufp->chgCData(oldp+206,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__control_unit_inst__DOT__opcode_i),7);
    bufp->chgCData(oldp+207,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__control_unit_inst__DOT__funct3_i),3);
    bufp->chgCData(oldp+208,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__control_unit_inst__DOT__funct7_i),7);
    bufp->chgIData(oldp+209,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__control_unit_inst__DOT__ctrl_signals_o),20);
    bufp->chgCData(oldp+210,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__control_unit_inst__DOT__instr_type_o),3);
    bufp->chgBit(oldp+211,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__control_unit_inst__DOT__eraise_o));
    bufp->chgBit(oldp+212,(vlSelfRef.top__DOT__core_inst__DOT__stage_id_inst__DOT__control_unit_inst__DOT__illegal_o));
    bufp->chgBit(oldp+213,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__clk_i));
    bufp->chgBit(oldp+214,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__rst_i));
    bufp->chgCData(oldp+215,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__ctrl_if_i),4);
    bufp->chgBit(oldp+216,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_rsp_valid_i));
    bufp->chgQData(oldp+217,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_rsp_i),41);
    bufp->chgQData(oldp+219,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__pc_redirect_i),33);
    bufp->chgBit(oldp+221,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_valid_o));
    bufp->chgBit(oldp+222,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_rsp_ready_o));
    bufp->chgWData(oldp+223,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_o),73);
    bufp->chgBit(oldp+226,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__info_if_o));
    bufp->chgWData(oldp+227,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__if_id_o),65);
    bufp->chgCData(oldp+230,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__fetch_epoch_q),4);
    bufp->chgCData(oldp+231,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__fetch_id_d),4);
    bufp->chgCData(oldp+232,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__fetch_id_q),4);
    bufp->chgBit(oldp+233,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_accepted));
    bufp->chgBit(oldp+234,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_rsp_accepted));
    bufp->chgIData(oldp+235,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__pc_q),32);
    bufp->chgIData(oldp+236,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__pc_issued_q),32);
    bufp->chgIData(oldp+237,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__pc_next),32);
    bufp->chgBit(oldp+238,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__pc_we));
    bufp->chgQData(oldp+239,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__pc_redirect_pending_q),33);
    bufp->chgWData(oldp+241,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_d),73);
    bufp->chgWData(oldp+244,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_q),73);
    bufp->chgBit(oldp+247,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_valid_d));
    bufp->chgBit(oldp+248,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_valid_q));
    bufp->chgBit(oldp+249,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_inflight_d));
    bufp->chgBit(oldp+250,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_inflight_q));
    bufp->chgBit(oldp+251,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_has_space));
    bufp->chgBit(oldp+252,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_req_issue));
    bufp->chgWData(oldp+253,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__if_id_d),65);
    bufp->chgWData(oldp+256,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__if_id_q),65);
    bufp->chgBit(oldp+259,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__imem_epoch_match));
    bufp->chgBit(oldp+260,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__program_counter_inst__DOT__clk_i));
    bufp->chgBit(oldp+261,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__program_counter_inst__DOT__rst_i));
    bufp->chgBit(oldp+262,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__program_counter_inst__DOT__pc_we_i));
    bufp->chgIData(oldp+263,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__program_counter_inst__DOT__pc_next_i),32);
    bufp->chgIData(oldp+264,(vlSelfRef.top__DOT__core_inst__DOT__stage_if_inst__DOT__program_counter_inst__DOT__pc_o),32);
    bufp->chgBit(oldp+265,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__clk_i));
    bufp->chgBit(oldp+266,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__rst_i));
    bufp->chgBit(oldp+267,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__ctrl_mem_i));
    bufp->chgWData(oldp+268,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__ex_mem_i),186);
    bufp->chgQData(oldp+274,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__dmem_rsp_i),41);
    bufp->chgWData(oldp+276,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__dmem_req_o),73);
    bufp->chgQData(oldp+279,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__info_mem_o),38);
    bufp->chgWData(oldp+281,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__mem_wb_o),186);
    bufp->chgWData(oldp+287,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__mem_wb_d),186);
    bufp->chgWData(oldp+293,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__mem_wb_q),186);
    bufp->chgBit(oldp+299,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__mem_we));
    bufp->chgIData(oldp+300,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__data_in),32);
    bufp->chgIData(oldp+301,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__data_out),32);
    bufp->chgBit(oldp+302,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__ram_inst__DOT__clk_i));
    bufp->chgBit(oldp+303,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__ram_inst__DOT__we_i));
    bufp->chgIData(oldp+304,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__ram_inst__DOT__addr_i),32);
    bufp->chgIData(oldp+305,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__ram_inst__DOT__data_i),32);
    bufp->chgIData(oldp+306,(vlSelfRef.top__DOT__core_inst__DOT__stage_mem_inst__DOT__ram_inst__DOT__data_o),32);
    bufp->chgBit(oldp+307,(vlSelfRef.top__DOT__core_inst__DOT__stage_wb_inst__DOT__clk));
    bufp->chgBit(oldp+308,(vlSelfRef.top__DOT__core_inst__DOT__stage_wb_inst__DOT__rst));
    bufp->chgWData(oldp+309,(vlSelfRef.top__DOT__core_inst__DOT__stage_wb_inst__DOT__mem_wb_i),186);
    bufp->chgCData(oldp+315,(vlSelfRef.top__DOT__core_inst__DOT__stage_wb_inst__DOT__rd_addr_o),5);
    bufp->chgIData(oldp+316,(vlSelfRef.top__DOT__core_inst__DOT__stage_wb_inst__DOT__rd_data_o),32);
    bufp->chgBit(oldp+317,(vlSelfRef.top__DOT__core_inst__DOT__stage_wb_inst__DOT__rd_we_o));
    bufp->chgBit(oldp+318,(vlSelfRef.top__DOT__core_inst__DOT__stage_wb_inst__DOT__info_wb_o));
    bufp->chgIData(oldp+319,(vlSelfRef.top__DOT__core_inst__DOT__stage_wb_inst__DOT__mem_data),32);
    bufp->chgBit(oldp+320,(vlSelfRef.top__DOT__rom_inst__DOT__clk_i));
    bufp->chgBit(oldp+321,(vlSelfRef.top__DOT__rom_inst__DOT__mem_req_valid_i));
    bufp->chgBit(oldp+322,(vlSelfRef.top__DOT__rom_inst__DOT__mem_rsp_ready_i));
    bufp->chgWData(oldp+323,(vlSelfRef.top__DOT__rom_inst__DOT__mem_req_i),73);
    bufp->chgBit(oldp+326,(vlSelfRef.top__DOT__rom_inst__DOT__mem_rsp_valid_o));
    bufp->chgQData(oldp+327,(vlSelfRef.top__DOT__rom_inst__DOT__mem_rsp_o),41);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Locals
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
